sudo: required
services: docker
language: generic

env:
  - TEST_CASE=1.4
  - TEST_CASE=1.4-flannel
  - TEST_CASE=1.4-calico
  - TEST_CASE=1.5
  - TEST_CASE=1.5-flannel
  - TEST_CASE=1.5-calico
  - TEST_CASE=1.6
  - TEST_CASE=src-1.6
  - TEST_CASE=src-master

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y liblz4-tool

script:
  - ./test.sh
